### ISSUE TITLE
[Minor] posts can't be upvoted or downvoted more than once

### ISSUE THREAD

**Issue by xCyziw** [Info442-team-2/friendly-mvp#45] opened 2019-12-06 20:56 UTC
**Describe the bug**
The upvote/downvote counter cannot be lower than -1 or higher than 1.

**To Reproduce**
1. Go to "Drake fan club"
2. Click on "Discussion"
3. Scroll down to the discussion posts
4. Attempt to upvote a post that is +1, or downvote a post that is -1

**Expected behavior**
I would expect to be able to upvote or downvote on any posts that I have not yet voted on. Instead, upvotes and downvotes cannot extend beyond the range of -1 to +1, so I cannot upvote or downvote if the resulting vote will cause the vote to be outside that range.

**Screenshots**
Screenshot: this is what the page looks like when I _haven't_ upvoted or downvoted anything. Posts that are already +1, I cannot upvote further.
![image](https://user-images.githubusercontent.com/14927028/70355634-7f7e5b80-1827-11ea-856b-66cdb4347a72.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by lockheedmartian** [comment] 2019-12-06 23:04
Duplicate of #32

**Closed by lockheedmartian** 2019-12-06 23:04 UTC
Labels: duplicate, minor
