### ISSUE TITLE
[minor] Clicking DASHBOARD doesn't bring you back to all groups if you search for something beforehand

### ISSUE THREAD

**Issue by anthonyqcn** [Info442-team-2/friendly-mvp#52] opened 2019-12-09 09:45 UTC
**Describe the bug**
After searching for groups using the search bar and then clicking the **dashboard link** in the top left part of the screen, it only returns you back to the groups that showed up when you searched. All of the other groups are not shown and the only way to get the normal list back is to search for an empty string, then click my profile, then click back to dashboards. This is a pretty annoying bug for users that prevents a major functionality of the app, but it does have a workaround which is why it's categorized as minor.

**To Reproduce**

- Type 'test lol' in search bar
- Click Search button
- Click on Dashboard
- Delete 'test lol' in search bar
- Click Search button
- Click My Profile
- Click on Dashboard

**Expected behavior**
See the dashboard normally populated with the default list of displayed groups without having to manually empty my search then go to profile and back to dashboard.

**Comment by lockheedmartian** [comment] 2019-12-10 04:00
Duplicate of #31

**Closed by lockheedmartian** 2019-12-10 04:00 UTC
Labels: minor
