### ISSUE TITLE
Access to Any users accounts in the system

### ISSUE THREAD

**Issue by deepforce** [Info442-team-2/friendly-mvp#41] opened 2019-12-06 03:44 UTC
**Describe the bug**
It's easy to access other people's accounts by typing different people's userID in the URL.

**To Reproduce**
1. Go to 'My Profile'
2. Change the last number in the URL to any number
3. Access other people's accounts

**Expected behavior**
There should be a verification process before access.

**Screenshots**
![image](https://user-images.githubusercontent.com/10813672/70294077-341c6c80-1797-11ea-897f-f4873cf66cd0.png)
![image](https://user-images.githubusercontent.com/10813672/70294080-37175d00-1797-11ea-8885-67eaf1ea9870.png)

**Desktop (please complete the following information):**
 - OS: [OSX]
 - Browser [chrome]

**Comment by lockheedmartian** [comment] 2019-12-06 21:49
This is by design. If you notice, you can't actually edit any user account that is not your own. I am closing this issue.

**Closed by lockheedmartian** 2019-12-06 21:49 UTC
Labels: major
