### ISSUE TITLE
Upvoting and Downvoting Doesn't Work

### ISSUE THREAD

**Issue by wochen96** [Info442-team-2/friendly-mvp#46] opened 2019-12-06 22:09 UTC
**Describe the bug**
The voting total can only have values of 1, 0, and -1. When I try to upvote a post with a value of 1, it does not work.

**To Reproduce**
1. Go to any post
2. Click on discussion
3. Upvote a post that has a vote count of 1

**Expected behavior**
The vote counts should have increased to 2.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by lockheedmartian** [comment] 2019-12-06 23:03
Duplicate of #32

**Closed by lockheedmartian** 2019-12-06 23:03 UTC
Labels: duplicate, major
