### ISSUE TITLE
Cannot undo search result

### ISSUE THREAD

**Issue by Aimee0103wu** [Info442-team-2/friendly-mvp#42] opened 2019-12-06 04:25 UTC
**Describe the bug**
After searching for a specific group, The dashboard is stuck at only showing the search result and there is no way to go back to the dashboard that shows the list of all groups. Not even clearing out the search bar or clicking on the logo can do that. 

**To Reproduce**
1. Go to dashboard
2. type in what you want to search (I searched for "kame")
3. hit search (and one group could be seen)
4. clear out the search bar or click on the logo
5. see error: nothing happens, the dashboard gets forever stuck on the search result

**Expected behavior**
I expect to be able to return to the general list of all groups in the dashboard after clearing out the search bar or even by clicking on the logo should take me back to the default dashboard view.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-12-05 at 8 24 30 PM" src="https://user-images.githubusercontent.com/46922678/70295909-7ba5f700-179d-11ea-8896-15d059cabf9d.png">

**Desktop (please complete the following information):**
 - mac book pro

 - Browser chrome
 - Version

**Comment by lockheedmartian** [comment] 2019-12-06 23:04
Duplicate of #39

**Closed by lockheedmartian** 2019-12-06 23:04 UTC
Labels: major
