### ISSUE TITLE
[minor] no user feedback if no results are found when clicking search button

### ISSUE THREAD

**Issue by Uyedacb** [Info442-team-2/friendly-mvp#53] opened 2019-12-09 09:59 UTC
**Describe the bug**
Website does not give any type of feedback whether a search is successful when clicking on the search button.

**To Reproduce**
1. Go to https://info442-team-2.github.io/friendly-mvp/#/groups
2. Click input non-existing group into search bar (I used "git")
3. No feedback is given as to whether the search was successful

**Expected behavior**
Expected some type of feedback saying no results were found. Can lead to confusion among users, might think the search is still loading because no feedback is given.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 78.0.3904.108 (64 bit)

**Comment by lockheedmartian** [comment] 2019-12-10 04:01
duplicate of #31

**Closed by lockheedmartian** 2019-12-10 04:01 UTC
Labels: duplicate, minor
