### ISSUE TITLE
[Major] Refreshing the page logs the user out

### ISSUE THREAD

**Issue by thebriando** [Info442-team-2/friendly-mvp#36] opened 2019-12-06 01:09 UTC
**Describe the bug**

**To Reproduce**
1. Go to the website
2. Sign in
3. Refresh
4. User is logged out

**Expected behavior**
User should not be logged out on refresh.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KeithSRoberts** [comment] 2019-12-06 02:08
Closing because this is a duplicate of #34

**Closed by KeithSRoberts** 2019-12-06 02:08 UTC
Labels: major
