### ISSUE TITLE
[minor] after using search bar and manually changing URL, clicking dashboard leads to no groups being displayed

### ISSUE THREAD

**Issue by Uyedacb** [Info442-team-2/friendly-mvp#54] opened 2019-12-09 10:09 UTC
**Describe the bug**
After searching for a non-existent group, Changing the URL from **https://info442-team-2.github.io/friendly-mvp/#/groups** to **https://info442-team-2.github.io/friendly-mvp/#** then going through the login process opens up a blank dashboard.

**To Reproduce**
1. Go to home page
2. Enter non-existent group into search bar
3. Click on search (I used "git" as my search entry)
4. Change the URL from **https://info442-team-2.github.io/friendly-mvp/#/groups** to **https://info442-team-2.github.io/friendly-mvp/#**
5. Login
6. See a blank dashboard

**Expected behavior**
Expected the dashboard to be populated with available groups

**Desktop**:
OS: Windows 10
Browser Chrome
Version 78.0.3904.108 (64 bit)

**Additional context**
Also, if you click on dashboard or the site icon, after these steps, the dashboard is still empty. This is probably because of an error with your search bar in general (just from reading some of the other issues).

**Comment by lockheedmartian** [comment] 2019-12-10 01:22
duplicate of #31

**Closed** 2019-12-10 01:22 UTC
Labels: duplicate, minor
