### ISSUE TITLE
the app disappear when I click go back button

### ISSUE THREAD

**Issue by FannieFann** [Info442-team-2/friendly-mvp#33] opened 2019-12-06 00:44 UTC
When I click "go back" button in the selection page, your web app disappears directly...

I suppose there should be something wrong with the redirecting function when changing pages:)

**Comment by KeithSRoberts** [comment] 2019-12-06 00:58
Can you clarify the steps to reproduce this bug? Perhaps screenshots? Browser? What machine are you on? We actually dont have any "go back" buttons on our site, could you clarify? Please add more details for this bug so we can observe it.

**Comment by FannieFann** [comment] 2019-12-06 01:06
[
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32870819/70286707-1217ef80-1781-11ea-8b61-953b33ed5fa5.png">
](url)

At this page, when I click go back button on the top left, the web disappears.
I'm using Safari on Mac.

**Comment by KeithSRoberts** [comment] 2019-12-06 01:09
Sorry but this still does not help us understand what the bug is, there is not back button on the top left or on the page what so ever. Can you please clarify this for us?

**Comment by KeithSRoberts** [comment] 2019-12-06 01:11
If you are referring to the back button included in your browser, can you please describe what you are seeing after navigating back in your history? You should be brought to the login page if you do so.

**Comment by FannieFann** [comment] 2019-12-06 01:21
Yes. It goes to my browser home page directly instead of login page.

**Comment by KeithSRoberts** [comment] 2019-12-06 01:55
Can you please provide steps to reproduce this? I have attempted to follow everything you say but am not able to reproduce this bug.

**Comment by lockheedmartian** [comment] 2019-12-06 22:47
This is intended and working correctly. The different "views" on the registration page are not different webpages (they are all apart of the registration page). If you want to go "back" you can refresh the page and start the registration process over.

I am closing this issue.

**Closed by lockheedmartian** 2019-12-06 22:47 UTC
Labels: major
